# Generated by Django 4.0.10 on 2023-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("little_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("", "")],
                default="default",
                max_length=100,
                verbose_name="role",
            ),
        ),
    ]
